services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3001
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=mood_api_db
      - POSTGRES_SSLMODE=disable
    ports: # expose for local test, in the future use API gateway
      - '3001:3001'
    depends_on:
      - postgres

  mood:
    build:
      context: .
      dockerfile: ./mood/Dockerfile
    container_name: mood
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3002
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=mood_api_db
      - POSTGRES_SSLMODE=disable
    ports: # expose for local test, in the future use API gateway
      - '3002:3002'
    depends_on:
      - postgres

  advice:
    build:
      context: .
      dockerfile: ./advice/Dockerfile
    container_name: advice
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3003
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=mood_api_db
      - POSTGRES_SSLMODE=disable
    ports: # expose for local test, in the future use API gateway
      - '3003:3003'
    depends_on:
      - postgres

  quote:
    build:
      context: .
      dockerfile: ./quote/Dockerfile
    container_name: quote
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3004
      - EXTERNAL_QUOTE_URL=https://zenquotes.io
    ports: # expose for local test, in the future use API gateway
      - '3004:3004'
    depends_on:
      - postgres

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: gateway
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - AUTH_URL=http://auth:3001
      - MOOD_URL=http://mood:3002
      - ADVICE_URL=http://advice:3003
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - mood
      - advice

volumes:
  pgdata:
